// Generated by go generate generate.go
// Created on 2019-02-04 22:45:38.88347 -0800 PST m=+0.002939462
package pantry

import (
	"github.com/hashicorp/hcl2/hcl"
	"github.com/hashicorp/hcl2/hcldec"
	"github.com/mikemackintosh/bakery/cli"
	"github.com/mikemackintosh/bakery/config"
	"github.com/zclconf/go-cty/cty"
)

// zip is a zip object
type Zip struct {
	PantryItem
	Name           string   `hcl:"name,label"`
	Config         hcl.Body `hcl:",remain"`
	DependsOn      []string `json:"depends_on"`
}

// Identifies the zip spec
var zipSpec = &hcldec.ObjectSpec{
	"depends_on": dependsOn,
	"source": &hcldec.AttrSpec{
		Name:     "source",
		Required: true,
		Type:     cty.String,
	},
}


// Parse the confgiuration with the provided spec
func (p *Zip) Parse(evalContext *hcl.EvalContext) error {
	cli.Debug(cli.INFO, "Preparing zip", p.Name)
	cfg, diags := hcldec.Decode(p.Config, zipSpec, evalContext)
	if len(diags) != 0 {
		for _, diag := range diags {
			cli.Debug(cli.INFO, "\t#", diag)
		}
		return fmt.Errorf("%s", diags.Errs()[0])
	}

	err := p.Populate(cfg, p)
	if err != nil {
		return err
	}

	return nil
}

// Bake will action the configuration
func (p *Zip) Bake() {
	//
}
